.cargo_test_template: &cargo_test
  stage: test
  script:
    - rustc --version && cargo --version
    - cargo test --jobs 1

stages:
  - test
  - release

stable:cargo:
  image: rustdocker/rust:stable
  <<: *cargo_test

build:docker:
  stage: release
  image: rustdocker/rust:stable
  script: 
    - docker build -t tabdos
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD gitlab.thearmabois.com
    - docker push $CI_COMMIT_REF_SLUG
