.cargo_test_template: &cargo_test
  stage: test
  script:
    - rustc --version && cargo --version
    - cargo test --jobs 1

before_script:
  - git config --global url."https://jakobklemm:${CI_JOB_TOKEN}@gitlab.thearmabois.com/engineering/ccp/tabuid.git".insteadOf "https://gitlab.thearmabois.com/engineering/ccp/tabuid.git"
  - git config --global url."https://jakobklemm:${CI_JOB_TOKEN}@gitlab.thearmabois.com/engineering/ccp/tabresp.git".insteadOf "https://gitlab.thearmabois.com/engineering/ccp/tabresp.git"

stages:
  - test
  - release

stable:cargo:
  image: rustdocker/rust:stable
  <<: *cargo_test

nightly:cargo:
  image: rustdocker/rust:nightly
  <<: *cargo_test

build:docker:
  stage: release
  script: 
    - docker build -t tabdos
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD gitlab.thearmabois.com
    - docker push $CI_COMMIT_REF_SLUG
